### ISSUE TITLE
The Citizen Watch Cannot Work With This

### ISSUE THREAD

**Issue by SeanChangX** [botanicfields/BF-018A#1] opened 2022-01-26 08:07 UTC
Hey, I like your project. And I wanna build one myself to my Citizen Radio Controlled Watch, but it seems that nothing gonna happen. So I wonder is there anything that can improve the signal? Or some tricks?

**Comment by uehara00** [comment] 2022-01-26 08:48
Would you please give me additional information?
(1) Are you using the "JJY antenna PCB"?
(2) Does the serial monitor show that the M5Atom is working well?
(3) What is the model number of Citizen Watch?

**Comment by SeanChangX** [comment] 2022-01-26 09:30
1. No. I just use the 1m wire and a 1kΩ resistance
2. Yes. And it continuously shows up the lastest time.
3.  CB5835-83E
https://www.citizenwatch.com.tw/productDetail.asp?sn=785
I wish that would be also work without the PCB temporarily.

**Comment by uehara00** [comment] 2022-01-26 11:28
How nice watch you have!
(1) Make sure that a 1m wire with a 1kΩ resistance is connected between the GPIO22 and the GND of the M5Atom. Since the watch receives the magnetic field of radio waves, the current flowing through the antenna is important.
An example of M5StickC is shown below.
https://www.hackster.io/botanicfields/generate-standard-radio-wave-jjy-with-ticker-of-m5stickc-0330e0

(3)
I searched FAQ in Japanese:
https://citizen.jp/faq/detail/id1275
Questions
How does a multi-station radio clock display the local time?
Answer
When you select a city, the time of that city is displayed and the station to receive is automatically selected.

It is my understanding, that the watch have to be set to city Tokyo because the program of BF-018A simulates the JJY signal in Japan.

I also found the manual.
https://www.citizenwatch-global.com/support/pdf/e660/e.pdf
https://www.citizenwatch-global.com/support/pdf-guide/e660/e.pdf
On page 49, it is said that, the watch receives the time signal every night, so please test over night in Tokyo time.
On page 29, it is said that, it may take 2 - 15 minutes to receive time signal, so please be patient when receiving the time signal  manually.
 
![49](https://user-images.githubusercontent.com/16858577/151154368-7d091935-3913-450b-b65d-5894a843706c.jpg)
![29](https://user-images.githubusercontent.com/16858577/151154376-25750db9-a240-43d0-8e1b-d7581456405c.jpg)

**Comment by SeanChangX** [comment] 2022-01-27 08:54
Yeah, you are right. After doing some tests with the emulator app, I think that was because the time zone(+8) that I choose was only matched with the BPC signal. 
So maybe I need to figure out how to generate the BPC signal instead of the JJY.
Thanks for your time.
![image](https://user-images.githubusercontent.com/65809302/151325322-1ff1b269-7772-4db1-a9c8-7179bbd45f1f.jpeg)

**Comment by uehara00** [comment] 2022-01-27 09:13
Thank you for verifying the cause. I would like to close this issue.

**Closed as completed by uehara00** 2022-01-27 09:13 UTC
